image: python:3.6

stages:
  - dcp_wide_test
  - 1000_cell_test
  - 100_cell_test

before_script:
  - apt-get -y update
  - apt-get -y install jq
  - pip install -r requirements.txt
  - export SWAGGER_URL="https://dss.$CI_COMMIT_REF_NAME.data.humancellatlas.org/v1/swagger.json"
  - mkdir -p ~/.config/hca
  - jq -n .DSSClient.swagger_url=env.SWAGGER_URL > ~/.config/hca/config.$CI_COMMIT_REF_NAME.json
  - export HCA_CONFIG_FILE=~/.config/hca/config.$CI_COMMIT_REF_NAME.json
  - aws configure set default.s3.multipart_threshold 64MB
  - aws configure set default.s3.multipart_chunksize 64MB
  - aws secretsmanager get-secret-value --region us-east-1 --secret-id dcp/dss/${CI_COMMIT_REF_NAME}/gcp-credentials.json | jq -r .SecretString > gcp-credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json

dcp_wide_test_SS2:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestSmartSeq2Run.test_smartseq2_run

dcp_wide_test_metadata_update:
  stage: dcp_wide_test
  only:
    - metadata-update
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestSmartSeq2Run.test_update

dcp_wide_test_optimus:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestOptimusRun.test_optimus_run
