image: python:3.6

stages:
  - dcp_wide_test
  - 1000_cell_test
  - 100_cell_test

before_script:
  - apt-get -y update
  - apt-get -y install jq
  - pip install -r requirements.txt
  - export DEPLOYMENT_ENV=$CI_COMMIT_REF_NAME
  - export AWS_DEFAULT_REGION=us-east-1
  - export SWAGGER_URL="https://dss.$DEPLOYMENT_ENV.data.humancellatlas.org/v1/swagger.json"
  - mkdir -p ~/.config/hca
  - jq -n .DSSClient.swagger_url=env.SWAGGER_URL > ~/.config/hca/config.$DEPLOYMENT_ENV.json
  - export HCA_CONFIG_FILE=~/.config/hca/config.$DEPLOYMENT_ENV.json
  - aws configure set default.s3.multipart_threshold 64MB
  - aws configure set default.s3.multipart_chunksize 64MB
  - aws secretsmanager get-secret-value --region us-east-1 --secret-id dcp/dss/${DEPLOYMENT_ENV}/gcp-credentials.json | jq -r .SecretString > gcp-credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json

dcp_wide_test_SS2:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestSmartSeq2Run.test_smartseq2_run

dcp_wide_test_metadata_update:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestSmartSeq2Run.test_update

dcp_wide_test_optimus:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestOptimusRun.test_optimus_run

dcp_wide_test_latest_metadata:
  stage: dcp_wide_test
    only:
      - integration
      - staging
    script:
      - python -m unittest tests.metadata_smoketests.test_latest_metadata_schema_e2e_dcp.TestLatestMetadataSchemaE2EDcp.test_latest_metadata_smart_seq_2
      - python -m unittest tests.metadata_smoketests.test_latest_metadata_schema_e2e_dcp.TestLatestMetadataSchemaE2EDcp.test_latest_metadata_10x
