image: python:3.6

stages:
  - dcp_wide_test
  - 1000_cell_test
  - 100_cell_test

before_script:
  - apt-get -y update
  - apt-get -y install jq
  - pip install -r requirements.txt
  - export SWAGGER_URL="https://dss.$CI_COMMIT_REF_NAME.data.humancellatlas.org/v1/swagger.json"
  - mkdir -p ~/.config/hca
  - jq -n .DSSClient.swagger_url=env.SWAGGER_URL > ~/.config/hca/config.$CI_COMMIT_REF_NAME.json
  - export HCA_CONFIG_FILE=~/.config/hca/config.$CI_COMMIT_REF_NAME.json
  - aws configure set default.s3.multipart_threshold 64MB
  - aws configure set default.s3.multipart_chunksize 64MB
  - aws secretsmanager get-secret-value --secret-id dcp/dss/${CI_COMMIT_REF_NAME}/gcp-credentials.json | jq -r .SecretString
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd -P)/gcp-credentials.json

dcp_wide_test_SS2:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.TestSmartSeq2Run.test_smartseq2_run

dcp_wide_test_10x:
  stage: dcp_wide_test
  only:
    - integration
    - staging
  script:
    - python -m unittest tests.integration.test_end_to_end_dcp.Test10xRun.test_10x_run

100_cell_test:
  stage: 100_cell_test
  only:
    refs:
      - master
      - schedules
    variables:
      - $COUNT == "100"
  script:
    - CI_COMMIT_REF_NAME=integration python -m unittest tests.scale.test_big_bundles.TestBigBundles.test_one_submission_with_100_bundles

1000_cell_test:
  stage: 1000_cell_test
  only:
    refs:
      - master
      - schedules
    variables:
      - $COUNT == "1000"
  script:
    - CI_COMMIT_REF_NAME=integration python -m unittest tests.scale.test_big_bundles.TestBigBundles.test_one_submission_with_1000_bundles
