language: python
python:
- 3.6
dist: trusty
install:
- pip install -r requirements.txt
addons:
  apt:
    packages:
    - jq
script:
- export SWAGGER_URL="https://dss.${TRAVIS_BRANCH}.data.humancellatlas.org/v1/swagger.json"
- mkdir -p ~/.config/hca
- jq -n .DSSClient.swagger_url=env.SWAGGER_URL > ~/.config/hca/config.${TRAVIS_BRANCH}.json
- export HCA_CONFIG_FILE=~/.config/hca/config.${TRAVIS_BRANCH}.json
- make test
branches:
  only:
  - staging
  - integration
env:
  global:
  - secure: UupQj71V5I+wg6dX19WrloVQUFXwECm2HGLupw4qkEeePWZbD4MPV7xXT+rIxHnXwz66o7GHg8xe2SVArdiouJsTWUHBFPswLkX8V7UIa8SH42UtO3Gs6p0UoqJvZO07NBBax3kHF5US0iNh6XunyPRFTz1cFIOfezeBdc8QuNcIf3sKQCjhJI857Z49qxZ5JsiPlixLxoyQ2UPb4IlAYKe/XX8ahfydXzYBkSlREW+1BwaXU27n8KGOCrWl6z+8WeVKyvPHzl9JqPS2YyS6JmVU+qYTdtSxfoFlDHY2C2ON0S7Wi15S+cIx7DA8FVyyrgJ9DeWFh/m8T8jgz3KlfZtPXSkNJhw/1EdgEhKPkRF5ZTxEaDOCd2sLeVz+n46R+EB/xm4tgaagDv32PtEJp4TMHI9M48t+k5iJWAz9d7EiM+4m7/moYaXJqgJyvwQ1RVIkrlxA0t939vsjNuFcdyy8vpin1rnxpeZ3o9jUuxhnix3BUDDk98VQMJd6oiCwPJXo6osj4TLVNBj7lq+MLJ+irgOHWcmF/+KLLJVyO/CV+I8Mcwd+pliw+oZaZHoRktzrNLgTfwBjF98kz7/ziWsg+W1Df4bZSYt8j/lcy53ax1SjXVNw8fmrRNiGUrCCBJuBIYVlTZcHgv4mN2NBCrr94YcSZ7E+TNQ/cevmwd4=
  - secure: A7B3ZX1CYtoewhPUvUpteqw7fYwMndrvewc5viErbUAR769QmOrvGUVfAo7WbDqLwnpj2GTR8LzxgKPKivl2knDoFHVqBM5ayZpKcsaYvzGofGYqPKNkY42501/rZM4Hd98deqCHDuQCG2TdHRbQhAaC990S3HMKMxNDkUeXCHwpKkBXLj2pe0dsmCkCWSHnnyXGmrHC9LSRCzlilcsUOolPc2F7jIp80blCP5LZuWRe1PaDjWwMaR2Z/L0fg+zWVfOlDreXDjnLx3rYtkPeKUPvaLTLxgB6mQpwKVW5IJhsR+q+qeHm7UL8MYtXL5ST2CuL++IInMGkv824GNKOmooplgIG3uXUoyiwwLTaksF6rE4/Ff2dgEJwP2r7ZZpiLQcJmVxEZ4H9R09K5Wavr73XNhqA5cAyiZCrkhTemkBT/pK9/Ang/ukILi6RjIdjGElAuS2+Kb3/AAoySl88x0Zwg3TOJKfIcXRcAyXF+Q64JR4P3GFA6/z3xKIzBa4Osj/lHdYddr+OvvLAZbwsY1Rh7xDsWaGx2redjJRfCZZCIsKP8AbeWBmOVl1QxL0TzDIKShenZ+Y8TgysQP2tQLOdev1ZxjnXIo6hvoD1lTkx7TbPyig8dAGXvZ8c2UxsGdW2VIko+a99Wa9wM7m8LfOVuw0brAahSPoeP6PxKiQ=
notifications:
  slack:
    secure: CuxoMgBpmwiEaUTzCpx+yQFfoXSILryA6b+W78mjlHKNaiYuoWvq4WOs2bc13aju8Lk6y2t1kSIdUW9A4n9xhRj53h+0W9xl1r3h8iM0C174d1yl8MRBAjdfoXJxRnru24+ZmLwVATJbJfZv+spXugkFCi6atqqV8a20XjpisuA5ssFWSlHqGcsoOnu/FHGZNi3bBsZbjOwspdk3RUERJ/kgiNgriX6s2JQ5aTn30G5E83Vx9W8PVWBqParqgOutnBPtKby7AEpIiB+wfQOaQFfpG7ufDENErsLbjJjiQcDaWPiEK2HHoxunvvk5hMCj3ND4mKAD0nYD6P6KK4x6p6nj+TXFzb/PCJCwnTBe5HD3QlTCg4ZaorEdDLD0/rXcT2wJ1+F8gMOxuT4FuKrX5KBS7Wwa7HwFYUpu/7JwP7mGU7El7U597b1aetFJ0AhqBWDI1dim0zWx8hJ4Py4vIyj8D7TCuH9FL3U33XKuRqatj7FlDcWtXF01xO6I5gzhqmlTegLbCJTNdjZacs7JXA8MH7xNxzdEFlpxFGHGea8DSy742vyO/bk+C4YH1iKh9XKY7fOhoKB/99RfLLv8q02H9m5SV1JXQSxd5bKHbMCDnN6+WciLll1BVRb4HcEDh+FY0rlqaCpzjYQCC1vT2zZlLZC9/PxswaZ/UyiU6h0=
  email:
  - mintteam@broadinstitute.org
