language: python
python:
  - 3.6
dist: trusty
install:
  - pip install -r requirements.txt
addons:
  apt:
    packages:
      - jq
script:
  - export SWAGGER_URL="https://dss.${TRAVIS_BRANCH}.data.humancellatlas.org/v1/swagger.json"
  - mkdir -p ~/.config/hca
  - jq -n .DSSClient.swagger_url=env.SWAGGER_URL > ~/.config/hca/config.${TRAVIS_BRANCH}.json
  - export HCA_CONFIG_FILE=~/.config/hca/config.${TRAVIS_BRANCH}.json
  - make test
branches:
  only:
    - staging
    - integration
notifications:
  slack:
    secure: AghFUYqaWS7u4IEBg3CfWdWiOXLENTPkfx9nrBf8CQ6f+Fchc8L1wYwD0j0bg8zIexdXb60syn9/MgC8QS5nkpSF4k8Js256yfAvATo6dnvY+NvHsu9WFTqSGmXhACpoYUVAEfE0cv/qnnZtVIhv5C6YPPw5Af1Efy2At6JiYizSQqWaNyIVrPANZuKk01ca6D7WLMC8oKF2NWYkHaipEHF9Q2+EWue7nnb2cpZKUOokiQO8pEIfAqN2iCLPSOU0R8miG1dQl4cUc5yGECCI5wSgvtxfV02IGthHYMXvoJb/bSttVmNuBsv1NMCqfl7lPPDNEZeYwKONnh3O4iANZu6aKC3Bq7YEawnzZbHDiagfa7HSmqdlXVbeCi0mWipCmzQEocV04LEYnHEX7pzi6hecknMx6u6hPVzQItcVPuhLHqnmT+GLXB0EZ/qdj6Eeb90oQcrWF5WqGY+XgIl+qzycx+3PlPnZRqevvhxoQ7GS3CNt4hjhKYIFxTN/rke9Vv2w0YzFAKHfDvWd0yEt5D3uUbHIcp87RrnW6IwmP9xmFqckgQQSfnUmWd5E3NeeUAZU88NAcGSoH9Z8/2eZ0CsJ+VdXBG3nLqqz3c6wxq+gUOMOxKANXEQm4IwC732lWPXede0oN6x4NfOMKoIqT7jRIbmJVzVu2UkcjIN1D84=
  email:
    - mintteam@broadinstitute.org
